-- Run this in Supabase SQL Editor before using the multi-grave UI.
-- Adds multiple grave slots per cemetery lot.

create table if not exists public.graves (
  grave_id bigint generated by default as identity primary key,
  lot_id integer not null references public.cemetery_lot(lot_id) on delete cascade,
  grave_label text not null,
  status text not null default 'Available',
  burial_id integer null references public.burial_record(burial_id) on delete set null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint graves_status_check check (status in ('Available', 'Reserved', 'Occupied')),
  constraint graves_lot_label_key unique (lot_id, grave_label)
);

alter table public.graves
  add column if not exists grave_label text,
  add column if not exists status text not null default 'Available',
  add column if not exists burial_id integer null
    references public.burial_record(burial_id) on delete set null,
  add column if not exists notes text null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists graves_lot_id_idx on public.graves(lot_id);
create index if not exists graves_status_idx on public.graves(status);
create index if not exists graves_burial_id_idx on public.graves(burial_id);

create or replace function public.set_graves_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_graves_updated_at on public.graves;

create trigger set_graves_updated_at
before update on public.graves
for each row
execute function public.set_graves_updated_at();

-- Ask Supabase/PostgREST to refresh its schema cache so the Flutter app
-- can immediately see public.graves through the REST API.
select pg_notify('pgrst', 'reload schema');
